---
- name: Packages upgrade
  apt:
    name: '*'
    state: present
- name: Packages installation and repo update
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - git
      - zsh
      - tmux
      - htop
      - nano
      - gpg-agent
      - python3-pip
      - python3-setuptools
      - virtualenv
      - openssh-server
    state: present
    update_cache: true
    cache_valid_time: 3600
- name: Disable password login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: Restart ssh
################ FIREWALL    
    # - name: Setup the firewall
    #   ufw: state=enabled policy=deny
    # - name: Allow ssh traffic
    #   ufw: rule=allow port={{ ssh_port }} proto=tcp
